version: 2

build:
   os: ubuntu-22.04
   tools:
      python: "3.11"

sphinx:
   configuration: sphinxdocs/conf.py

formats: all

python:
   install:
      - requirements: sphinxdocs/requirements.txt
