    if(var_array[0].inDomain(-1))
    {
        if(var_array[0].inDomain(1))
        {
            if(var_array[1].inDomain(-1))
            {
                if(var_array[1].inDomain(1))
                {
                    if(var_array[2].inDomain(-1))
                    {
                        if(var_array[2].inDomain(1))
                        {
                            if(var_array[3].inDomain(-1))
                            {
                                if(!var_array[3].inDomain(1))
                                {
                                    if(var_array[4].inDomain(-2))
                                    {
                                        if(!var_array[4].inDomain(2))
                                        {
                                            if(!var_array[4].inDomain(0))
                                            {
                                                var_array[2].removeFromDomain(-1);
                                            }
                                        }
                                    }
                                    else
                                    {
                                        if(var_array[4].inDomain(2))
                                        {
                                            if(!var_array[4].inDomain(0))
                                            {
                                                var_array[2].removeFromDomain(1);
                                            }
                                        }
                                    }
                                }
                            }
                            else
                            {
                                if(var_array[4].inDomain(-2))
                                {
                                    if(!var_array[4].inDomain(2))
                                    {
                                        if(!var_array[4].inDomain(0))
                                        {
                                            var_array[2].removeFromDomain(1);
                                        }
                                    }
                                }
                                else
                                {
                                    if(var_array[4].inDomain(2))
                                    {
                                        if(!var_array[4].inDomain(0))
                                        {
                                            var_array[2].removeFromDomain(-1);
                                        }
                                    }
                                }
                            }
                        }
                        else
                        {
                            if(var_array[3].inDomain(-1))
                            {
                                if(var_array[3].inDomain(1))
                                {
                                    if(var_array[4].inDomain(-2))
                                    {
                                        if(!var_array[4].inDomain(2))
                                        {
                                            if(!var_array[4].inDomain(0))
                                            {
                                                var_array[3].removeFromDomain(-1);
                                            }
                                        }
                                    }
                                    else
                                    {
                                        if(var_array[4].inDomain(2))
                                        {
                                            if(!var_array[4].inDomain(0))
                                            {
                                                var_array[3].removeFromDomain(1);
                                            }
                                        }
                                    }
                                }
                                else
                                {
                                    var_array[4].removeFromDomain(-2);
                                }
                            }
                            else
                            {
                                var_array[4].removeFromDomain(2);
                            }
                        }
                    }
                    else
                    {
                        if(var_array[3].inDomain(-1))
                        {
                            if(var_array[3].inDomain(1))
                            {
                                if(var_array[4].inDomain(-2))
                                {
                                    if(!var_array[4].inDomain(2))
                                    {
                                        if(!var_array[4].inDomain(0))
                                        {
                                            var_array[3].removeFromDomain(1);
                                        }
                                    }
                                }
                                else
                                {
                                    if(var_array[4].inDomain(2))
                                    {
                                        if(!var_array[4].inDomain(0))
                                        {
                                            var_array[3].removeFromDomain(-1);
                                        }
                                    }
                                }
                            }
                            else
                            {
                                var_array[4].removeFromDomain(2);
                            }
                        }
                        else
                        {
                            var_array[4].removeFromDomain(-2);
                        }
                    }
                }
                else
                {
                    if(var_array[2].inDomain(-1))
                    {
                        if(var_array[2].inDomain(1))
                        {
                            if(var_array[3].inDomain(-1))
                            {
                                if(var_array[3].inDomain(1))
                                {
                                    if(var_array[4].inDomain(-2))
                                    {
                                        if(!var_array[4].inDomain(2))
                                        {
                                            if(!var_array[4].inDomain(0))
                                            {
                                                var_array[0].removeFromDomain(-1);
                                            }
                                        }
                                    }
                                    else
                                    {
                                        if(var_array[4].inDomain(2))
                                        {
                                            if(!var_array[4].inDomain(0))
                                            {
                                                var_array[0].removeFromDomain(1);
                                            }
                                        }
                                    }
                                }
                                else
                                {
                                    if(var_array[4].inDomain(-2))
                                    {
                                        if(!var_array[4].inDomain(2))
                                        {
                                            if(!var_array[4].inDomain(0))
                                            {
                                                var_array[0].removeFromDomain(-1);
                                                var_array[2].removeFromDomain(-1);
                                            }
                                        }
                                    }
                                    else
                                    {
                                        if(var_array[4].inDomain(2))
                                        {
                                            if(!var_array[4].inDomain(0))
                                            {
                                                var_array[0].removeFromDomain(1);
                                                var_array[2].removeFromDomain(1);
                                            }
                                        }
                                    }
                                }
                            }
                            else
                            {
                                if(var_array[4].inDomain(-2))
                                {
                                    if(!var_array[4].inDomain(2))
                                    {
                                        if(!var_array[4].inDomain(0))
                                        {
                                            var_array[0].removeFromDomain(-1);
                                            var_array[2].removeFromDomain(1);
                                        }
                                    }
                                }
                                else
                                {
                                    if(var_array[4].inDomain(2))
                                    {
                                        if(!var_array[4].inDomain(0))
                                        {
                                            var_array[0].removeFromDomain(1);
                                            var_array[2].removeFromDomain(-1);
                                        }
                                    }
                                }
                            }
                        }
                        else
                        {
                            if(var_array[3].inDomain(-1))
                            {
                                if(var_array[3].inDomain(1))
                                {
                                    if(var_array[4].inDomain(-2))
                                    {
                                        if(!var_array[4].inDomain(2))
                                        {
                                            if(!var_array[4].inDomain(0))
                                            {
                                                var_array[0].removeFromDomain(-1);
                                                var_array[3].removeFromDomain(-1);
                                            }
                                        }
                                    }
                                    else
                                    {
                                        if(var_array[4].inDomain(2))
                                        {
                                            if(!var_array[4].inDomain(0))
                                            {
                                                var_array[0].removeFromDomain(1);
                                                var_array[3].removeFromDomain(1);
                                            }
                                        }
                                    }
                                }
                                else
                                {
                                    var_array[4].removeFromDomain(-2);
                                    if(var_array[4].inDomain(0))
                                    {
                                        if(!var_array[4].inDomain(2))
                                        {
                                            var_array[0].removeFromDomain(-1);
                                        }
                                    }
                                    else
                                    {
                                        var_array[0].removeFromDomain(1);
                                    }
                                }
                            }
                            else
                            {
                                var_array[4].removeFromDomain(2);
                                if(var_array[4].inDomain(-2))
                                {
                                    if(!var_array[4].inDomain(0))
                                    {
                                        var_array[0].removeFromDomain(-1);
                                    }
                                }
                                else
                                {
                                    var_array[0].removeFromDomain(1);
                                }
                            }
                        }
                    }
                    else
                    {
                        if(var_array[3].inDomain(-1))
                        {
                            if(var_array[3].inDomain(1))
                            {
                                if(var_array[4].inDomain(-2))
                                {
                                    if(!var_array[4].inDomain(2))
                                    {
                                        if(!var_array[4].inDomain(0))
                                        {
                                            var_array[0].removeFromDomain(-1);
                                            var_array[3].removeFromDomain(1);
                                        }
                                    }
                                }
                                else
                                {
                                    if(var_array[4].inDomain(2))
                                    {
                                        if(!var_array[4].inDomain(0))
                                        {
                                            var_array[0].removeFromDomain(1);
                                            var_array[3].removeFromDomain(-1);
                                        }
                                    }
                                }
                            }
                            else
                            {
                                var_array[4].removeFromDomain(2);
                                if(var_array[4].inDomain(-2))
                                {
                                    if(!var_array[4].inDomain(0))
                                    {
                                        var_array[0].removeFromDomain(-1);
                                    }
                                }
                                else
                                {
                                    var_array[0].removeFromDomain(1);
                                }
                            }
                        }
                        else
                        {
                            var_array[4].removeFromDomain(-2);
                            if(var_array[4].inDomain(0))
                            {
                                if(!var_array[4].inDomain(2))
                                {
                                    var_array[0].removeFromDomain(-1);
                                }
                            }
                            else
                            {
                                var_array[0].removeFromDomain(1);
                            }
                        }
                    }
                }
            }
            else
            {
                if(var_array[2].inDomain(-1))
                {
                    if(var_array[2].inDomain(1))
                    {
                        if(var_array[3].inDomain(-1))
                        {
                            if(var_array[3].inDomain(1))
                            {
                                if(var_array[4].inDomain(-2))
                                {
                                    if(!var_array[4].inDomain(2))
                                    {
                                        if(!var_array[4].inDomain(0))
                                        {
                                            var_array[0].removeFromDomain(1);
                                        }
                                    }
                                }
                                else
                                {
                                    if(var_array[4].inDomain(2))
                                    {
                                        if(!var_array[4].inDomain(0))
                                        {
                                            var_array[0].removeFromDomain(-1);
                                        }
                                    }
                                }
                            }
                            else
                            {
                                if(var_array[4].inDomain(-2))
                                {
                                    if(!var_array[4].inDomain(2))
                                    {
                                        if(!var_array[4].inDomain(0))
                                        {
                                            var_array[0].removeFromDomain(1);
                                            var_array[2].removeFromDomain(-1);
                                        }
                                    }
                                }
                                else
                                {
                                    if(var_array[4].inDomain(2))
                                    {
                                        if(!var_array[4].inDomain(0))
                                        {
                                            var_array[0].removeFromDomain(-1);
                                            var_array[2].removeFromDomain(1);
                                        }
                                    }
                                }
                            }
                        }
                        else
                        {
                            if(var_array[4].inDomain(-2))
                            {
                                if(!var_array[4].inDomain(2))
                                {
                                    if(!var_array[4].inDomain(0))
                                    {
                                        var_array[0].removeFromDomain(1);
                                        var_array[2].removeFromDomain(1);
                                    }
                                }
                            }
                            else
                            {
                                if(var_array[4].inDomain(2))
                                {
                                    if(!var_array[4].inDomain(0))
                                    {
                                        var_array[0].removeFromDomain(-1);
                                        var_array[2].removeFromDomain(-1);
                                    }
                                }
                            }
                        }
                    }
                    else
                    {
                        if(var_array[3].inDomain(-1))
                        {
                            if(var_array[3].inDomain(1))
                            {
                                if(var_array[4].inDomain(-2))
                                {
                                    if(!var_array[4].inDomain(2))
                                    {
                                        if(!var_array[4].inDomain(0))
                                        {
                                            var_array[0].removeFromDomain(1);
                                            var_array[3].removeFromDomain(-1);
                                        }
                                    }
                                }
                                else
                                {
                                    if(var_array[4].inDomain(2))
                                    {
                                        if(!var_array[4].inDomain(0))
                                        {
                                            var_array[0].removeFromDomain(-1);
                                            var_array[3].removeFromDomain(1);
                                        }
                                    }
                                }
                            }
                            else
                            {
                                var_array[4].removeFromDomain(-2);
                                if(var_array[4].inDomain(0))
                                {
                                    if(!var_array[4].inDomain(2))
                                    {
                                        var_array[0].removeFromDomain(1);
                                    }
                                }
                                else
                                {
                                    var_array[0].removeFromDomain(-1);
                                }
                            }
                        }
                        else
                        {
                            var_array[4].removeFromDomain(2);
                            if(var_array[4].inDomain(-2))
                            {
                                if(!var_array[4].inDomain(0))
                                {
                                    var_array[0].removeFromDomain(1);
                                }
                            }
                            else
                            {
                                var_array[0].removeFromDomain(-1);
                            }
                        }
                    }
                }
                else
                {
                    if(var_array[3].inDomain(-1))
                    {
                        if(var_array[3].inDomain(1))
                        {
                            if(var_array[4].inDomain(-2))
                            {
                                if(!var_array[4].inDomain(2))
                                {
                                    if(!var_array[4].inDomain(0))
                                    {
                                        var_array[0].removeFromDomain(1);
                                        var_array[3].removeFromDomain(1);
                                    }
                                }
                            }
                            else
                            {
                                if(var_array[4].inDomain(2))
                                {
                                    if(!var_array[4].inDomain(0))
                                    {
                                        var_array[0].removeFromDomain(-1);
                                        var_array[3].removeFromDomain(-1);
                                    }
                                }
                            }
                        }
                        else
                        {
                            var_array[4].removeFromDomain(2);
                            if(var_array[4].inDomain(-2))
                            {
                                if(!var_array[4].inDomain(0))
                                {
                                    var_array[0].removeFromDomain(1);
                                }
                            }
                            else
                            {
                                var_array[0].removeFromDomain(-1);
                            }
                        }
                    }
                    else
                    {
                        var_array[4].removeFromDomain(-2);
                        if(var_array[4].inDomain(0))
                        {
                            if(!var_array[4].inDomain(2))
                            {
                                var_array[0].removeFromDomain(1);
                            }
                        }
                        else
                        {
                            var_array[0].removeFromDomain(-1);
                        }
                    }
                }
            }
        }
        else
        {
            if(var_array[1].inDomain(-1))
            {
                if(var_array[1].inDomain(1))
                {
                    if(var_array[2].inDomain(-1))
                    {
                        if(var_array[2].inDomain(1))
                        {
                            if(var_array[3].inDomain(-1))
                            {
                                if(var_array[3].inDomain(1))
                                {
                                    if(var_array[4].inDomain(-2))
                                    {
                                        if(!var_array[4].inDomain(2))
                                        {
                                            if(!var_array[4].inDomain(0))
                                            {
                                                var_array[1].removeFromDomain(-1);
                                            }
                                        }
                                    }
                                    else
                                    {
                                        if(var_array[4].inDomain(2))
                                        {
                                            if(!var_array[4].inDomain(0))
                                            {
                                                var_array[1].removeFromDomain(1);
                                            }
                                        }
                                    }
                                }
                                else
                                {
                                    if(var_array[4].inDomain(-2))
                                    {
                                        if(!var_array[4].inDomain(2))
                                        {
                                            if(!var_array[4].inDomain(0))
                                            {
                                                var_array[1].removeFromDomain(-1);
                                                var_array[2].removeFromDomain(-1);
                                            }
                                        }
                                    }
                                    else
                                    {
                                        if(var_array[4].inDomain(2))
                                        {
                                            if(!var_array[4].inDomain(0))
                                            {
                                                var_array[1].removeFromDomain(1);
                                                var_array[2].removeFromDomain(1);
                                            }
                                        }
                                    }
                                }
                            }
                            else
                            {
                                if(var_array[4].inDomain(-2))
                                {
                                    if(!var_array[4].inDomain(2))
                                    {
                                        if(!var_array[4].inDomain(0))
                                        {
                                            var_array[1].removeFromDomain(-1);
                                            var_array[2].removeFromDomain(1);
                                        }
                                    }
                                }
                                else
                                {
                                    if(var_array[4].inDomain(2))
                                    {
                                        if(!var_array[4].inDomain(0))
                                        {
                                            var_array[1].removeFromDomain(1);
                                            var_array[2].removeFromDomain(-1);
                                        }
                                    }
                                }
                            }
                        }
                        else
                        {
                            if(var_array[3].inDomain(-1))
                            {
                                if(var_array[3].inDomain(1))
                                {
                                    if(var_array[4].inDomain(-2))
                                    {
                                        if(!var_array[4].inDomain(2))
                                        {
                                            if(!var_array[4].inDomain(0))
                                            {
                                                var_array[1].removeFromDomain(-1);
                                                var_array[3].removeFromDomain(-1);
                                            }
                                        }
                                    }
                                    else
                                    {
                                        if(var_array[4].inDomain(2))
                                        {
                                            if(!var_array[4].inDomain(0))
                                            {
                                                var_array[1].removeFromDomain(1);
                                                var_array[3].removeFromDomain(1);
                                            }
                                        }
                                    }
                                }
                                else
                                {
                                    var_array[4].removeFromDomain(-2);
                                    if(var_array[4].inDomain(0))
                                    {
                                        if(!var_array[4].inDomain(2))
                                        {
                                            var_array[1].removeFromDomain(-1);
                                        }
                                    }
                                    else
                                    {
                                        var_array[1].removeFromDomain(1);
                                    }
                                }
                            }
                            else
                            {
                                var_array[4].removeFromDomain(2);
                                if(var_array[4].inDomain(-2))
                                {
                                    if(!var_array[4].inDomain(0))
                                    {
                                        var_array[1].removeFromDomain(-1);
                                    }
                                }
                                else
                                {
                                    var_array[1].removeFromDomain(1);
                                }
                            }
                        }
                    }
                    else
                    {
                        if(var_array[3].inDomain(-1))
                        {
                            if(var_array[3].inDomain(1))
                            {
                                if(var_array[4].inDomain(-2))
                                {
                                    if(!var_array[4].inDomain(2))
                                    {
                                        if(!var_array[4].inDomain(0))
                                        {
                                            var_array[1].removeFromDomain(-1);
                                            var_array[3].removeFromDomain(1);
                                        }
                                    }
                                }
                                else
                                {
                                    if(var_array[4].inDomain(2))
                                    {
                                        if(!var_array[4].inDomain(0))
                                        {
                                            var_array[1].removeFromDomain(1);
                                            var_array[3].removeFromDomain(-1);
                                        }
                                    }
                                }
                            }
                            else
                            {
                                var_array[4].removeFromDomain(2);
                                if(var_array[4].inDomain(-2))
                                {
                                    if(!var_array[4].inDomain(0))
                                    {
                                        var_array[1].removeFromDomain(-1);
                                    }
                                }
                                else
                                {
                                    var_array[1].removeFromDomain(1);
                                }
                            }
                        }
                        else
                        {
                            var_array[4].removeFromDomain(-2);
                            if(var_array[4].inDomain(0))
                            {
                                if(!var_array[4].inDomain(2))
                                {
                                    var_array[1].removeFromDomain(-1);
                                }
                            }
                            else
                            {
                                var_array[1].removeFromDomain(1);
                            }
                        }
                    }
                }
                else
                {
                    var_array[4].removeFromDomain(-2);
                    if(var_array[2].inDomain(-1))
                    {
                        if(var_array[2].inDomain(1))
                        {
                            if(var_array[3].inDomain(-1))
                            {
                                if(!var_array[3].inDomain(1))
                                {
                                    if(var_array[4].inDomain(0))
                                    {
                                        if(!var_array[4].inDomain(2))
                                        {
                                            var_array[2].removeFromDomain(-1);
                                        }
                                    }
                                    else
                                    {
                                        var_array[2].removeFromDomain(1);
                                    }
                                }
                            }
                            else
                            {
                                if(var_array[4].inDomain(0))
                                {
                                    if(!var_array[4].inDomain(2))
                                    {
                                        var_array[2].removeFromDomain(1);
                                    }
                                }
                                else
                                {
                                    var_array[2].removeFromDomain(-1);
                                }
                            }
                        }
                        else
                        {
                            if(var_array[3].inDomain(-1))
                            {
                                if(var_array[3].inDomain(1))
                                {
                                    if(var_array[4].inDomain(0))
                                    {
                                        if(!var_array[4].inDomain(2))
                                        {
                                            var_array[3].removeFromDomain(-1);
                                        }
                                    }
                                    else
                                    {
                                        var_array[3].removeFromDomain(1);
                                    }
                                }
                                else
                                {
                                    var_array[4].removeFromDomain(0);
                                }
                            }
                            else
                            {
                                var_array[4].removeFromDomain(2);
                            }
                        }
                    }
                    else
                    {
                        if(var_array[3].inDomain(-1))
                        {
                            if(var_array[3].inDomain(1))
                            {
                                if(var_array[4].inDomain(0))
                                {
                                    if(!var_array[4].inDomain(2))
                                    {
                                        var_array[3].removeFromDomain(1);
                                    }
                                }
                                else
                                {
                                    var_array[3].removeFromDomain(-1);
                                }
                            }
                            else
                            {
                                var_array[4].removeFromDomain(2);
                            }
                        }
                        else
                        {
                            var_array[4].removeFromDomain(0);
                        }
                    }
                }
            }
            else
            {
                var_array[4].removeFromDomain(2);
                if(var_array[2].inDomain(-1))
                {
                    if(var_array[2].inDomain(1))
                    {
                        if(var_array[3].inDomain(-1))
                        {
                            if(!var_array[3].inDomain(1))
                            {
                                if(var_array[4].inDomain(-2))
                                {
                                    if(!var_array[4].inDomain(0))
                                    {
                                        var_array[2].removeFromDomain(-1);
                                    }
                                }
                                else
                                {
                                    var_array[2].removeFromDomain(1);
                                }
                            }
                        }
                        else
                        {
                            if(var_array[4].inDomain(-2))
                            {
                                if(!var_array[4].inDomain(0))
                                {
                                    var_array[2].removeFromDomain(1);
                                }
                            }
                            else
                            {
                                var_array[2].removeFromDomain(-1);
                            }
                        }
                    }
                    else
                    {
                        if(var_array[3].inDomain(-1))
                        {
                            if(var_array[3].inDomain(1))
                            {
                                if(var_array[4].inDomain(-2))
                                {
                                    if(!var_array[4].inDomain(0))
                                    {
                                        var_array[3].removeFromDomain(-1);
                                    }
                                }
                                else
                                {
                                    var_array[3].removeFromDomain(1);
                                }
                            }
                            else
                            {
                                var_array[4].removeFromDomain(-2);
                            }
                        }
                        else
                        {
                            var_array[4].removeFromDomain(0);
                        }
                    }
                }
                else
                {
                    if(var_array[3].inDomain(-1))
                    {
                        if(var_array[3].inDomain(1))
                        {
                            if(var_array[4].inDomain(-2))
                            {
                                if(!var_array[4].inDomain(0))
                                {
                                    var_array[3].removeFromDomain(1);
                                }
                            }
                            else
                            {
                                var_array[3].removeFromDomain(-1);
                            }
                        }
                        else
                        {
                            var_array[4].removeFromDomain(0);
                        }
                    }
                    else
                    {
                        var_array[4].removeFromDomain(-2);
                    }
                }
            }
        }
    }
    else
    {
        if(var_array[1].inDomain(-1))
        {
            if(var_array[1].inDomain(1))
            {
                if(var_array[2].inDomain(-1))
                {
                    if(var_array[2].inDomain(1))
                    {
                        if(var_array[3].inDomain(-1))
                        {
                            if(var_array[3].inDomain(1))
                            {
                                if(var_array[4].inDomain(-2))
                                {
                                    if(!var_array[4].inDomain(2))
                                    {
                                        if(!var_array[4].inDomain(0))
                                        {
                                            var_array[1].removeFromDomain(1);
                                        }
                                    }
                                }
                                else
                                {
                                    if(var_array[4].inDomain(2))
                                    {
                                        if(!var_array[4].inDomain(0))
                                        {
                                            var_array[1].removeFromDomain(-1);
                                        }
                                    }
                                }
                            }
                            else
                            {
                                if(var_array[4].inDomain(-2))
                                {
                                    if(!var_array[4].inDomain(2))
                                    {
                                        if(!var_array[4].inDomain(0))
                                        {
                                            var_array[1].removeFromDomain(1);
                                            var_array[2].removeFromDomain(-1);
                                        }
                                    }
                                }
                                else
                                {
                                    if(var_array[4].inDomain(2))
                                    {
                                        if(!var_array[4].inDomain(0))
                                        {
                                            var_array[1].removeFromDomain(-1);
                                            var_array[2].removeFromDomain(1);
                                        }
                                    }
                                }
                            }
                        }
                        else
                        {
                            if(var_array[4].inDomain(-2))
                            {
                                if(!var_array[4].inDomain(2))
                                {
                                    if(!var_array[4].inDomain(0))
                                    {
                                        var_array[1].removeFromDomain(1);
                                        var_array[2].removeFromDomain(1);
                                    }
                                }
                            }
                            else
                            {
                                if(var_array[4].inDomain(2))
                                {
                                    if(!var_array[4].inDomain(0))
                                    {
                                        var_array[1].removeFromDomain(-1);
                                        var_array[2].removeFromDomain(-1);
                                    }
                                }
                            }
                        }
                    }
                    else
                    {
                        if(var_array[3].inDomain(-1))
                        {
                            if(var_array[3].inDomain(1))
                            {
                                if(var_array[4].inDomain(-2))
                                {
                                    if(!var_array[4].inDomain(2))
                                    {
                                        if(!var_array[4].inDomain(0))
                                        {
                                            var_array[1].removeFromDomain(1);
                                            var_array[3].removeFromDomain(-1);
                                        }
                                    }
                                }
                                else
                                {
                                    if(var_array[4].inDomain(2))
                                    {
                                        if(!var_array[4].inDomain(0))
                                        {
                                            var_array[1].removeFromDomain(-1);
                                            var_array[3].removeFromDomain(1);
                                        }
                                    }
                                }
                            }
                            else
                            {
                                var_array[4].removeFromDomain(-2);
                                if(var_array[4].inDomain(0))
                                {
                                    if(!var_array[4].inDomain(2))
                                    {
                                        var_array[1].removeFromDomain(1);
                                    }
                                }
                                else
                                {
                                    var_array[1].removeFromDomain(-1);
                                }
                            }
                        }
                        else
                        {
                            var_array[4].removeFromDomain(2);
                            if(var_array[4].inDomain(-2))
                            {
                                if(!var_array[4].inDomain(0))
                                {
                                    var_array[1].removeFromDomain(1);
                                }
                            }
                            else
                            {
                                var_array[1].removeFromDomain(-1);
                            }
                        }
                    }
                }
                else
                {
                    if(var_array[3].inDomain(-1))
                    {
                        if(var_array[3].inDomain(1))
                        {
                            if(var_array[4].inDomain(-2))
                            {
                                if(!var_array[4].inDomain(2))
                                {
                                    if(!var_array[4].inDomain(0))
                                    {
                                        var_array[1].removeFromDomain(1);
                                        var_array[3].removeFromDomain(1);
                                    }
                                }
                            }
                            else
                            {
                                if(var_array[4].inDomain(2))
                                {
                                    if(!var_array[4].inDomain(0))
                                    {
                                        var_array[1].removeFromDomain(-1);
                                        var_array[3].removeFromDomain(-1);
                                    }
                                }
                            }
                        }
                        else
                        {
                            var_array[4].removeFromDomain(2);
                            if(var_array[4].inDomain(-2))
                            {
                                if(!var_array[4].inDomain(0))
                                {
                                    var_array[1].removeFromDomain(1);
                                }
                            }
                            else
                            {
                                var_array[1].removeFromDomain(-1);
                            }
                        }
                    }
                    else
                    {
                        var_array[4].removeFromDomain(-2);
                        if(var_array[4].inDomain(0))
                        {
                            if(!var_array[4].inDomain(2))
                            {
                                var_array[1].removeFromDomain(1);
                            }
                        }
                        else
                        {
                            var_array[1].removeFromDomain(-1);
                        }
                    }
                }
            }
            else
            {
                var_array[4].removeFromDomain(2);
                if(var_array[2].inDomain(-1))
                {
                    if(var_array[2].inDomain(1))
                    {
                        if(var_array[3].inDomain(-1))
                        {
                            if(!var_array[3].inDomain(1))
                            {
                                if(var_array[4].inDomain(-2))
                                {
                                    if(!var_array[4].inDomain(0))
                                    {
                                        var_array[2].removeFromDomain(-1);
                                    }
                                }
                                else
                                {
                                    var_array[2].removeFromDomain(1);
                                }
                            }
                        }
                        else
                        {
                            if(var_array[4].inDomain(-2))
                            {
                                if(!var_array[4].inDomain(0))
                                {
                                    var_array[2].removeFromDomain(1);
                                }
                            }
                            else
                            {
                                var_array[2].removeFromDomain(-1);
                            }
                        }
                    }
                    else
                    {
                        if(var_array[3].inDomain(-1))
                        {
                            if(var_array[3].inDomain(1))
                            {
                                if(var_array[4].inDomain(-2))
                                {
                                    if(!var_array[4].inDomain(0))
                                    {
                                        var_array[3].removeFromDomain(-1);
                                    }
                                }
                                else
                                {
                                    var_array[3].removeFromDomain(1);
                                }
                            }
                            else
                            {
                                var_array[4].removeFromDomain(-2);
                            }
                        }
                        else
                        {
                            var_array[4].removeFromDomain(0);
                        }
                    }
                }
                else
                {
                    if(var_array[3].inDomain(-1))
                    {
                        if(var_array[3].inDomain(1))
                        {
                            if(var_array[4].inDomain(-2))
                            {
                                if(!var_array[4].inDomain(0))
                                {
                                    var_array[3].removeFromDomain(1);
                                }
                            }
                            else
                            {
                                var_array[3].removeFromDomain(-1);
                            }
                        }
                        else
                        {
                            var_array[4].removeFromDomain(0);
                        }
                    }
                    else
                    {
                        var_array[4].removeFromDomain(-2);
                    }
                }
            }
        }
        else
        {
            var_array[4].removeFromDomain(-2);
            if(var_array[2].inDomain(-1))
            {
                if(var_array[2].inDomain(1))
                {
                    if(var_array[3].inDomain(-1))
                    {
                        if(!var_array[3].inDomain(1))
                        {
                            if(var_array[4].inDomain(0))
                            {
                                if(!var_array[4].inDomain(2))
                                {
                                    var_array[2].removeFromDomain(-1);
                                }
                            }
                            else
                            {
                                var_array[2].removeFromDomain(1);
                            }
                        }
                    }
                    else
                    {
                        if(var_array[4].inDomain(0))
                        {
                            if(!var_array[4].inDomain(2))
                            {
                                var_array[2].removeFromDomain(1);
                            }
                        }
                        else
                        {
                            var_array[2].removeFromDomain(-1);
                        }
                    }
                }
                else
                {
                    if(var_array[3].inDomain(-1))
                    {
                        if(var_array[3].inDomain(1))
                        {
                            if(var_array[4].inDomain(0))
                            {
                                if(!var_array[4].inDomain(2))
                                {
                                    var_array[3].removeFromDomain(-1);
                                }
                            }
                            else
                            {
                                var_array[3].removeFromDomain(1);
                            }
                        }
                        else
                        {
                            var_array[4].removeFromDomain(0);
                        }
                    }
                    else
                    {
                        var_array[4].removeFromDomain(2);
                    }
                }
            }
            else
            {
                if(var_array[3].inDomain(-1))
                {
                    if(var_array[3].inDomain(1))
                    {
                        if(var_array[4].inDomain(0))
                        {
                            if(!var_array[4].inDomain(2))
                            {
                                var_array[3].removeFromDomain(1);
                            }
                        }
                        else
                        {
                            var_array[3].removeFromDomain(-1);
                        }
                    }
                    else
                    {
                        var_array[4].removeFromDomain(2);
                    }
                }
                else
                {
                    var_array[4].removeFromDomain(0);
                }
            }
        }
    }
