
ConstraintDef constraint_list[] = {
{ "element" , CT_ELEMENT, 3,{ read_list , read_var , read_var }, STATIC_CT },
{ "element_one" , CT_ELEMENT_ONE, 3,{ read_list , read_var , read_var }, STATIC_CT },
{ "watchelement" , CT_WATCHED_ELEMENT, 3,{ read_list , read_var , read_var }, DYNAMIC_CT },
{ "watchelement_one" , CT_WATCHED_ELEMENT_ONE, 3,{ read_list , read_var , read_var }, DYNAMIC_CT },
{ "gacelement-deprecated" , CT_GACELEMENT, 3,{ read_list , read_var , read_var }, STATIC_CT },
{ "alldiff" , CT_ALLDIFF, 1,{ read_list }, STATIC_CT },
{ "gacalldiff" , CT_GACALLDIFF, 1,{ read_list }, STATIC_CT },
{ "gcc" , CT_GCC, 3,{ read_list , read_constant_list , read_list }, STATIC_CT },
{ "diseq" , CT_DISEQ, 2,{ read_var , read_var }, STATIC_CT },
{ "__reify_diseq" , CT_DISEQ_REIFY, 3,{ read_var , read_var , read_bool_var }, STATIC_CT },
{ "eq" , CT_EQ, 2,{ read_var , read_var }, STATIC_CT },
{ "__reify_eq" , CT_EQ_REIFY, 3,{ read_var , read_var , read_bool_var }, STATIC_CT },
{ "minuseq" , CT_MINUSEQ, 2,{ read_var , read_var }, STATIC_CT },
{ "__reify_minuseq" , CT_MINUSEQ_REIFY, 3,{ read_var , read_var , read_bool_var }, STATIC_CT },
{ "abs" , CT_ABS, 2,{ read_var , read_var }, STATIC_CT },
{ "ineq" , CT_INEQ, 3,{ read_var , read_var , read_constant }, STATIC_CT },
{ "watchneq" , CT_WATCHED_NEQ, 2,{ read_var , read_var }, DYNAMIC_CT },
{ "watchless" , CT_WATCHED_LESS, 2,{ read_var , read_var }, DYNAMIC_CT },
{ "lexleq" , CT_LEXLEQ, 2,{ read_list , read_list }, STATIC_CT },
{ "lexless" , CT_LEXLESS, 2,{ read_list , read_list }, STATIC_CT },
{ "max" , CT_MAX, 2,{ read_list , read_var }, STATIC_CT },
{ "min" , CT_MIN, 2,{ read_list , read_var }, STATIC_CT },
{ "occurrence" , CT_OCCURRENCE, 3,{ read_list , read_constant , read_var }, STATIC_CT },
{ "occurrenceleq" , CT_LEQ_OCCURRENCE, 3,{ read_list , read_constant , read_constant }, STATIC_CT },
{ "occurrencegeq" , CT_GEQ_OCCURRENCE, 3,{ read_list , read_constant , read_constant }, STATIC_CT },
{ "product" , CT_PRODUCT2, 2,{ read_2_vars , read_var }, STATIC_CT },
{ "difference" , CT_DIFFERENCE, 2,{ read_2_vars , read_var }, STATIC_CT },
{ "weightedsumleq" , CT_WEIGHTLEQSUM, 3,{ read_constant_list , read_list , read_var }, STATIC_CT },
{ "weightedsumgeq" , CT_WEIGHTGEQSUM, 3,{ read_constant_list , read_list , read_var }, STATIC_CT },
{ "sumgeq" , CT_GEQSUM, 2,{ read_list , read_var }, STATIC_CT },
{ "sumleq" , CT_LEQSUM, 2,{ read_list , read_var }, STATIC_CT },
{ "watchsumgeq" , CT_WATCHED_GEQSUM, 2,{ read_list , read_constant }, DYNAMIC_CT },
{ "watchsumleq" , CT_WATCHED_LEQSUM, 2,{ read_list , read_constant }, DYNAMIC_CT },
{ "table" , CT_WATCHED_TABLE, 2,{ read_list , read_tuples }, DYNAMIC_CT },
{ "negativetable" , CT_WATCHED_NEGATIVE_TABLE, 2,{ read_list , read_tuples }, DYNAMIC_CT },
{ "watchvecneq" , CT_WATCHED_VECNEQ, 2,{ read_list , read_list }, DYNAMIC_CT },
{ "litsumgeq" , CT_WATCHED_LITSUM, 3,{ read_list , read_constant_list , read_constant }, DYNAMIC_CT },
{ "pow" , CT_POW, 2,{ read_2_vars , read_var }, STATIC_CT },
{ "div" , CT_DIV, 2,{ read_2_vars , read_var }, STATIC_CT },
{ "modulo" , CT_MODULO, 2,{ read_2_vars , read_var }, STATIC_CT },
{ "gadget" , CT_GADGET, 1,{ read_list }, STATIC_CT },
{ "disabled-or" , CT_WATCHED_OR, 1,{ read_list }, DYNAMIC_CT },
{ "watchvecexists_less" , CT_WATCHED_VEC_OR_LESS, 2,{ read_list , read_list }, DYNAMIC_CT },
{ "watchvecexists_and" , CT_WATCHED_VEC_OR_AND, 2,{ read_list , read_list }, DYNAMIC_CT },
{ "hamming" , CT_WATCHED_HAMMING, 3,{ read_list , read_list , read_constant }, DYNAMIC_CT },
{ "watched-or" , CT_WATCHED_NEW_OR, 1,{ read_constraint_list }, DYNAMIC_CT },
{ "watched-and" , CT_WATCHED_NEW_AND, 1,{ read_constraint_list }, DYNAMIC_CT },
{ "w-inset" , CT_WATCHED_INSET, 2,{ read_var , read_constant_list }, DYNAMIC_CT },
{ "w-notinset" , CT_WATCHED_NOT_INSET, 2,{ read_var , read_constant_list }, DYNAMIC_CT },
{ "w-inrange" , CT_WATCHED_INRANGE, 2,{ read_var , read_constant_list }, DYNAMIC_CT },
{ "w-notinrange" , CT_WATCHED_NOT_INRANGE, 2,{ read_var , read_constant_list }, DYNAMIC_CT },
{ "w-literal" , CT_WATCHED_LIT, 2,{ read_var , read_constant }, DYNAMIC_CT },
{ "w-notliteral" , CT_WATCHED_NOTLIT, 2,{ read_var , read_constant }, DYNAMIC_CT },
{ "reify" , CT_REIFY, 2,{ read_constraint , read_bool_var }, DYNAMIC_CT },
{ "reifyimply-quick" , CT_REIFYIMPLY_QUICK, 2,{ read_constraint , read_bool_var }, DYNAMIC_CT },
{ "reifyimply" , CT_REIFYIMPLY, 2,{ read_constraint , read_bool_var }, DYNAMIC_CT },
};
