name: CI

# Trigger the workflow on push or pull request
on:
  workflow_dispatch:
    inputs:
      # see https://github.com/marketplace/actions/debugging-with-tmate
      debug_enabled:
        description: 'Run the build with tmate debugging enabled'
        type: boolean
  pull_request:
  push:
  schedule:
    # Every day at 2:30 AM UTC
    - cron: '30 2 * * *'



jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        shell: [bash]
    steps:
      - uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: "Config"
        run: |
                mkdir bin-quick
                cd bin-quick
                python3 ../configure.py --quick
      
      - name: "Build"
        run: |
                cd bin-quick
                make -j2
      
      - name: "First test"
        run: |
              cd test_instances
              bash ./run_tests.sh ../bin-quick/minion
      
      - name: "Rust tests"
        run: |
              export PATH=$PATH:$HOME/.cargo/bin
              cd tester
              cargo run --release -- --minion ../bin-quick/minion
